version: '3.11'

services:
  auth-api:
    build: .
    container_name: fastapi-auth-service
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=secret-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload